services:
  cert-monitor:
    build: .
    ports:
      - "9393:9393"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - cert-monitor-net

networks:
  cert-monitor-net:
    driver: bridge