services:
  cert-monitor:
    build: .
    ports:
      - "9393:9393"  # metrics port
    env_file:
      - .env
    environment:
      - RUBY_ENV=production
    volumes:
      - ./certs/ssl:/app/certs/ssl:ro  # 只读挂载证书目录
    restart: unless-stopped
    networks:
      - cert-monitor-net

networks:
  cert-monitor-net:
    driver: bridge