{{- if and .Values.istio.enabled .Values.istio.virtualService.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "cert-monitor.fullname" . }}-vs
  labels:
    {{- include "cert-monitor.labels" . | nindent 4 }}
spec:
  hosts:
  {{- range .Values.istio.virtualService.hosts }}
  - {{ . | quote }}
  {{- end }}
  gateways:
  {{- range .Values.istio.virtualService.gateways }}
  - {{ . | quote }}
  {{- end }}
  http:
  - match:
    - uri:
        prefix: /metrics
    route:
    - destination:
        host: {{ include "cert-monitor.fullname" . }}
        port:
          number: {{ .Values.service.port }}
    timeout: 30s
    retries:
      attempts: 3
      perTryTimeout: 10s
  - match:
    - uri:
        prefix: /health
    route:
    - destination:
        host: {{ include "cert-monitor.fullname" . }}
        port:
          number: {{ .Values.service.port }}
    timeout: 10s
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ include "cert-monitor.fullname" . }}
        port:
          number: {{ .Values.service.port }}
    timeout: 30s
{{- end }}