{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "helm-charts.fullname" . }}-vs
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helm-charts.labels" . | nindent 4 }}
spec:
  hosts:
    {{- range .Values.istio.hosts }}
    - {{ . | quote }}
    {{- end }}
  gateways:
    - {{ include "helm-charts.fullname" . }}-gateway
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: {{ include "helm-charts.fullname" . }}
            port:
              number: {{ .Values.service.port }}
{{- end }}